@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue May 02 07:03:55 +0200 2023
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 0fb19cecad794f9d9cdf6f62b77a55d4 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot MEM1_TB_Config_behav xil_defaultlib.MEM1_TB_Config -log elaborate.log"
call xelab  -wto 0fb19cecad794f9d9cdf6f62b77a55d4 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot MEM1_TB_Config_behav xil_defaultlib.MEM1_TB_Config -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
